//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bvyhct_caobangEntities : DbContext
    {
        public bvyhct_caobangEntities()
            : base("name=bvyhct_caobangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoCauToChuc> CoCauToChucs { get; set; }
        public virtual DbSet<tblBenhvien> tblBenhviens { get; set; }
        public virtual DbSet<tblChuyenkhoa> tblChuyenkhoas { get; set; }
        public virtual DbSet<tblChuyenmuc> tblChuyenmucs { get; set; }
        public virtual DbSet<tblHomthu> tblHomthus { get; set; }
        public virtual DbSet<tblPhacdodieutri> tblPhacdodieutris { get; set; }
        public virtual DbSet<tblPhanhoi> tblPhanhois { get; set; }
        public virtual DbSet<tblTaikhoan> tblTaikhoans { get; set; }
        public virtual DbSet<tblTailieu> tblTailieux { get; set; }
        public virtual DbSet<tblThongke> tblThongkes { get; set; }
        public virtual DbSet<tblTintuc> tblTintucs { get; set; }
    }
}
