//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBenhvien
    {
        public int benhvien_id { get; set; }
        public string benhvien_tenbenhvien { get; set; }
        public string benhvien_diachi { get; set; }
        public string benhvien_dienthoai { get; set; }
        public string benhvien_fax { get; set; }
        public string benhvien_email { get; set; }
        public string benhvien_website { get; set; }
        public string benhvien_hotline { get; set; }
        public string benhvien_lienhehanhchinh { get; set; }
        public string benhvien_capcuu { get; set; }
        public string benhvien_logo { get; set; }
        public string benhvien_gioithieu { get; set; }
        public int benhvien_phanloai { get; set; }
        public string benhvien_slogan { get; set; }
        public string benhvien_dvchuquan { get; set; }
    }
}
