//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChuyenkhoa
    {
        public int chuyenkhoa_id { get; set; }
        public string chuyenkhoa_name { get; set; }
    }
}
