//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHomthu
    {
        public int homthu_id { get; set; }
        public int homthu_user_id { get; set; }
        public string homthu_user_noidunghoi { get; set; }
        public System.DateTime homthu_ngayhoi { get; set; }
        public Nullable<int> homthu_bacsi_id { get; set; }
        public string homthu_bacsi_giaidap { get; set; }
        public Nullable<System.DateTime> homthu_ngaygiaidap { get; set; }
        public int homthu_phanloai { get; set; }
        public int homthu_trangthai { get; set; }
        public int homthu_chuyenmuc { get; set; }
        public Nullable<int> homthu_kieu_traloi { get; set; }
    }
}
