//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhacdodieutri
    {
        public int phacdo_id { get; set; }
        public string phacdo_tieude { get; set; }
        public string phacdo_noidung { get; set; }
        public int phacdo_chuyenkhoa { get; set; }
    }
}
