//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhanhoi
    {
        public int phanhoi_id { get; set; }
        public string phanhoi_hoten { get; set; }
        public string phanhoi_email { get; set; }
        public string phanhoi_sdt { get; set; }
        public string phanhoi_tieude { get; set; }
        public string phanhoi_noidung { get; set; }
        public System.DateTime phanhoi_ngaygui { get; set; }
    }
}
