//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTailieu
    {
        public int tailieu_id { get; set; }
        public string tailieu_path { get; set; }
        public string tailieu_tieude { get; set; }
        public System.DateTime tailieu_ngaytao { get; set; }
        public int tailieu_phanloai { get; set; }
    }
}
