//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongke
    {
        public int id { get; set; }
        public System.DateTime datetime { get; set; }
        public int day { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public int online { get; set; }
        public int visit { get; set; }
        public int sum_today { get; set; }
        public int sum_all { get; set; }
    }
}
