//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaikhoan
    {
        public int taikhoan_id { get; set; }
        public string taikhoan_tendangnhap { get; set; }
        public string taikhoan_matkhau { get; set; }
        public string taikhoan_quyen { get; set; }
        public string taikhoan_hoten { get; set; }
        public string taikhoan_gioitinh { get; set; }
        public string taikhoan_ngaysinh { get; set; }
        public string taikhoan_chucvu { get; set; }
        public string taikhoan_dienthoai { get; set; }
        public string taikhoan_email { get; set; }
        public string taikhoan_image { get; set; }
    }
}
