//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICB.AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTintuc
    {
        public int tintuc_id { get; set; }
        public string tintuc_tieude { get; set; }
        public string tintuc_image { get; set; }
        public System.DateTime tintuc_ngaydang { get; set; }
        public string tintuc_nguoidang { get; set; }
        public int tintuc_phanloai { get; set; }
        public int tintuc_trangthai { get; set; }
        public string tintuc_motangan { get; set; }
        public string tintuc_noidung { get; set; }
    }
}
